### ISSUE TITLE
Scratch cache isn't actually deleting files

### ISSUE THREAD

**Issue by Aldair502** [emmett1/scratchpkg#42]
i mean this should delete the cache right?. it doesn't delete packages or sources cache

**Comment by emmett1** [comment]
It should delete **old** packages and sources. Are you sure its not work for you?

**Comment by Aldair502** [comment]
> It should delete **old** packages and sources. Are you sure its not work for you?

Oh, so it checks /usr/ports and find the latest version before delete it?. i thought it just was like pacman -Scc
